### ISSUE TITLE
UOSL issues with steps 03_T3_50 and 03_T3_42

### ISSUE THREAD

**Issue by LAMaglan** [IMI-ConcePTION/DP3-MS-SLE#13]
We at UOSL get errors for the following steps

`03_T3_42_compute_monthly_point_prevalence_MS`
![DP4_03_T3_42_error](https://user-images.githubusercontent.com/29206211/223675332-c3537e61-4267-4910-8cf5-f31d3ea83a68.png)

and

`03_T3_50_aggregate_prevalence_MS_error`
![DP4_03_T3_50_aggregate_prevalence_MS_error](https://user-images.githubusercontent.com/29206211/223675352-503e01b4-e8c0-4909-9530-3c32a57bae42.png)

**Comment by DavideMessinaARS** [comment]
The dataset that exit step 03_42 goes into step 03_50, that's what is causing the second issue.
I will take a look at the first one and release a correction hopefully soon.

**Comment by DavideMessinaARS** [comment]
I've created a new release https://github.com/IMI-ConcePTION/DP3-MS-SLE/releases/tag/v1.0.1

I think this should fix the errors that you find but it might be necessary a stricter approach to the usage of memory.

**Comment by LAMaglan** [comment]
Rstudio crashed after the final step, so am unable to check if these steps also had errors.
![DP4_crash_end](https://user-images.githubusercontent.com/29206211/223948991-9414a717-7c02-48f7-b3fa-ea96a1e41f0e.png)

Is there some output I can check / series lines that I can rerun?

**Comment by DavideMessinaARS** [comment]
In g_intermediate you should find the two datasets D4_prevalence_average_point_**_OUTCOME_***
***_OUTCOME_** = MS, SLE

Those are the output of step 03_42, if they are there then the step has finished.

If you want to check the I/O of other steps they represented in a DAG here: https://imi-conception.github.io/DP3-MS-SLE/

Anyway, I don't think it was this script that crashed your server since I see it arrived at the end of it. If I'm wrong please tell me and we will try to find the underlying cause of it.

**Comment by LAMaglan** [comment]
The files you mentioned are not in `g_intermediate/`, so I guess step 03_42 failed.
(see screenshot)
![g_intermediate_DP3](https://user-images.githubusercontent.com/29206211/224253899-68f45288-72e2-4de1-9f06-93f844e1c862.png)


What is your suggestion? Should I run the "LOAD PARAMETERS" steps, then run 
step 03_42 to get the error message (with stack trace)? Although I assume that it is
memory related

**Comment by LAMaglan** [comment]
A quick fix would be to add some calls to `gc()` within the step/function, at least after anything
that is potentially memory intensive.

**Comment by DavideMessinaARS** [comment]
> The files you mentioned are not in g_intermediate/, so I guess step 03_42 failed.

My fault, the datasets should be in g_output

> A quick fix would be to add some calls to gc() within the step/function

In theory that won't change anything. Garbage collecting in R is done automatically. What I could do is remove the pointer to the object in memory with `rm()`.

> Should I run the "LOAD PARAMETERS" steps, then run step 03_42 to get the error message (with stack trace)? Although I assume that it is memory related

Check again in g_output if the datasets are there. If they are not then download [CountPrevalence.zip](https://github.com/IMI-ConcePTION/DP3-MS-SLE/files/10941235/CountPrevalence.zip) and extract it in p_macro.
Then rerun the parameters and step 03_42.

**Comment by LAMaglan** [comment]
the files you mentioned are in not in g_output. I will take the updated "CountPrevalence.R", run step 03_42 and let you know how that goes

In some cases, R does not do automatic garbage collection, depending on the OS, etc.
We have locally used it in some cases.
See here
http://adv-r.had.co.nz/memory.html

**Comment by DavideMessinaARS** [comment]
On the link you mentioned I read:

> Despite what you might have read elsewhere, there’s never any need to call gc() yourself. R will automatically run garbage collection whenever it needs more space; if you want to see when that is, call gcinfo(TRUE). The only reason you might want to call gc() is to ask R to return memory to the operating system. However, even that might not have any effect: older versions of Windows had no way for a program to return memory to the OS.

Anyway if you feel it might make a difference you can try to add it.

**Comment by LAMaglan** [comment]
It is not something I feel, but for certain cases / OS's, it makes a difference (especially for "long" for loops).
If you want, I can show you RAM usage before and after a call to `gc()` after a computationally heavy process
on our windows server (but is not really the scope / point of this issue anymore).

Anyway, will let you know what is the status of 03 T3_42

**Comment by LAMaglan** [comment]
There is a different memory issue:
`Error: cannot allocate vector of size 3.8 Gb`
![03_t3_42_memory_error](https://user-images.githubusercontent.com/29206211/224640595-ada3d99e-52fb-454b-8f53-3f183bd4848e.png)

**Comment by DavideMessinaARS** [comment]
This time I removed any time period a person is not in the population directly inside the function which gives you the error.

Please download [Corrections.zip](https://github.com/IMI-ConcePTION/DP3-MS-SLE/files/10956033/Corrections.zip) and move CountPrevalence.R to p_macro and step 03_T3_42 to p_steps then rerun the parameters and launch again 03_T3_42

**Comment by LAMaglan** [comment]
Memory issue in a different step

![03_t3_42_memory_error_2](https://user-images.githubusercontent.com/29206211/225295167-9dbc7edc-0339-47e6-8a5c-63b95fab9bf0.png)

Let me know if there is something you want me to run / check out

**Comment by DavideMessinaARS** [comment]
I've fixed step 03_42 in https://github.com/IMI-ConcePTION/DP3-MS-SLE/releases/tag/v1.0.2

**Comment by LAMaglan** [comment]
Step 03_42 finished for us, but get an error for the next step, 03_50
![DP3_03_T3_50_error](https://user-images.githubusercontent.com/29206211/226836765-b7b04426-e496-4164-8483-047beca323be.png)
It seems like there is something wrong with the "D4_prevalence_average_point_MS.rds" output from 03_42,
as it is not loaded correctly in 03_50 (see "manual" load with readRDS)
![DP3_specific_file_error](https://user-images.githubusercontent.com/29206211/226839474-21a5e254-8ef9-469e-b3af-9e46b3c85094.png)
All the other RDS files in g_output can be loaded correctly
![DP3_g_output](https://user-images.githubusercontent.com/29206211/226840140-b64905a7-04a8-4b2f-807d-e4449155ccc8.png)

**Comment by LAMaglan** [comment]
No, that one (and the other RDS files in g_output) can be loaded (see screenshot)
![DP3_files](https://user-images.githubusercontent.com/29206211/226848007-e02b38e7-c3fc-4f44-97bc-04efdd4e1c3a.png)

**Comment by DavideMessinaARS** [comment]
I think the dataset D4_prevalence_average_point_MS has been corrupted or saved incorrectly. I don't have a clear idea on how it happened.

I can give you two options now:
- Run again 03_42 just for MS and then the next steps
- Run 03_50 only for SLE and then run 03_42 just for MS while in the meantime you can check SLE results

**Comment by LAMaglan** [comment]
Ok, I think it makes sense to rerun 03_42 for MS. Will let you know

**Comment by LAMaglan** [comment]
The file was indeed corrupted.  The cause was probably recent issues with the filesystem (NFS) on the UOSL server. The two steps have now finished without error. You may close this issue.
