### ISSUE TITLE
RDRU_FISABIO:

### ISSUE THREAD

**Issue by erarasfisabio** [IMI-ConcePTION/DP3-MS-SLE#17]
Dear @DavideMessinaARS, as request we have start with the DP-3 script.

Following the instructions we have indicated the dirinput and also de dirpregnancy. The parameters chunk has run successfully, but in the next steps we have got some errors.

A) # CLEAN THE SPELLS
> launch_step("p_steps/01_T2_40_clean_spells.R")
Error in merge.data.table(D3_output_spells_category, D3_PERSONS, all.x = T,  : 
  Elements listed in `by` must be valid column names in x and y
In addition: Warning message:
In merge.data.table(D3_output_spells_category, D3_PERSONS, all.x = T,  :
  You are trying to join data.tables where 'x' argument is 0 columns data.table.
Timing stopped at: 0.72 0 2.2

B) Also happen for : launch_step("p_steps/01_T2_50_selection_criteria_from_PERSON_to_study_population.R"); launch_step("p_steps/02_T3_10_create_study_population.R"); launch_step("p_steps/03_T2_10_create_study_population_baseline_variables.R"); launch_step("p_steps/03_T2_20_create_main_components.R"); launch_step("p_steps/03_T2_21_create_components_MS.R"); launch_step("p_steps/03_T2_22_create_components_SLE.R"); launch_step("p_steps/03_T2_30_create_algorithms_MS.R"); launch_step("p_steps/03_T3_40_compute_period_prevalence_MS.R"); launch_step("p_steps/03_T3_41_compute_persontime_prevalence_MS.R"); launch_step("p_steps/03_T3_42_compute_monthly_point_prevalence_MS.R"); launch_step("p_steps/04_T4_10_create_N_women_and_ranges_MS.R"); launch_step("p_steps/04_T4_30_aggregate_prevalence.R")
**Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'L:/EnfermedadesRaras/ConcePTION_IMI/WP7/ConcePTION/Data characterisation/DP3-MS-SLE.v2.3.0/g_intermediate/D3_clean_spells.rds', probable reason 'No such file or directory'
Timing stopped at: 0.76 0.02 0.83**

In case it was usefull, we inform to you that for our DAP, the name in the table CDM_SOURCE is: RDRU_FISABIO. Moreover, from our previous experience in identifying diseases through ICD codes, we need to confirm with you whether the ICD10ES (Spanish version of the ICD10 codes) are included in the script. Fortunately, for Multiple Sclerosis the CIE10ES codes are the same as for CIE10, so if this is the case, the only information that would be modified would be the "event_record_vocabulary"== "CIE10ES", as this is the value that appears in our tables.

Please would you help us with this. 
We look forward to hearing from you. 
Best wishes, 
Laia

**Comment by DavideMessinaARS** [comment]
To summarize:

- The name of your DAP should already be "RDRU_FISABIO". Olga gave me the suggestion to change it.
- I can copy the ICD10 to a new vocabulary in the script but it's not clear to me which one: ICD10ES or CIE10ES?
- The error in 01_T2_40 seems a result of not finding the correct columns in some of the datasets. On my end, using a "D3_pregnancy_final" dummy dataset seems to be working so I don't really understand what's going on.
- Error in 01_T2_50 is cascading from 01_T2_40

Can we schedule call on Monday? At which time are you free? Morning?

**Comment by DavideMessinaARS** [comment]
I may have found the problem of step 01_T2_40.
On my simulated data, I found how to generate an error in step 01_T2_20 and it may be possible this is the cause of the other ones in the subsequent steps.

I've created a new release https://github.com/IMI-ConcePTION/DP3-MS-SLE/releases/tag/v2.3.1.

Feel free to close this issue if that fixes your problem

**Comment by erarasfisabio** [comment]
Dear @DavideMessinaARS 
Thank you for your feedback. 
I tried to run it, but we got many errors when downloading the parameters. 
I'm ok to meet, I'm available today 12:30 to 16. And tomorrow 9 to 15:00

I look forward to hearing from you
Laia,

**Comment by erarasfisabio** [comment]
Dear @DavideMessinaARS 
Thanks for the modifications, 
I had some errors with the script this morning but now it seems to be working fine.
I'll let you know how it worked, as soon as it finishes running.

Laia,

**Comment by erarasfisabio** [comment]
Dear @DavideMessinaARS, 
Please note that the script stills returns the same error. 
_____________
"Warning message:
In data.table::fwrite(df, file_name) :
  Input has no columns; creating an empty file at 'L:/EnfermedadesRaras/ConcePTION_IMI/WP7/ConcePTION/Data characterisation/DP3-MS-SLE.v2.3.1/g_intermediate/D3_output_spells_category.csv' and exiting."
_______________
After this warning, the next steps return: 
__
launch_step("p_steps/01_T2_40_clean_spells.R")
Error in merge.data.table(D3_output_spells_category, D3_PERSONS, all.x = T,  : 
  Elements listed in `by` must be valid column names in x and y
In addition: Warning message:
In merge.data.table(D3_output_spells_category, D3_PERSONS, all.x = T,  :
  You are trying to join data.tables where 'x' argument is 0 columns data.table.
__
launch_step("p_steps/01_T2_50_selection_criteria_from_PERSON_to_study_population.R")
[1] "CREATE EXCLUSION CRITERIA FOR STUDY POPULATION"
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'L:/EnfermedadesRaras/ConcePTION_IMI/WP7/ConcePTION/Data characterisation/DP3-MS-SLE.v2.3.1/g_intermediate/D3_clean_spells.rds', probable reason 'No such file or directory'
__ 
And the same for all subsequent actions performed using the p_steps folder.

**Please, let us know your availability. 
Today I will be available until 16. And on Tuesday and Wednesday from 9 to 15:15.

Best,
Laia**

**Comment by erarasfisabio** [comment]
Thank you very much for your support
Best, 
Laia

**Comment by DavideMessinaARS** [comment]
For future reference: the problem was incorrect meanings for OBSERVATION_PERIODS.
The overlap for the single subpopulation between pregnancies and medicinal data availability returned 0 spell with returning an error in step 01_T2_20
