### ISSUE TITLE
error p_steps10_T3_20

### ISSUE THREAD

**Issue by mariebeslay** [IMI-ConcePTION/DP3-MS-SLE#23]
What steps do I need to run exactly ? 

I have this error :  

> launch_step("p_steps/10_T3_20_create_prevalence_of_exclusive_use_MSmeds_in_MSpregnancy_trimesters.R")
Error in eval(jsub, SDenv, parent.frame()) :
object 'number_before_pregnancy_3' not found

**Comment by DavideMessinaARS** [comment]
Step 10_T3_20 is necessary for template 3. 
Strange that before it was not giving you an error. Maybe changing the entry and exit of pregnant cohort of the DU had an impact. I will investigate

**Comment by mariebeslay** [comment]
The step 09_T3_20_match.R also does not work, but we do not have the matching in EFEMERIS, so it seemed normal. But maybe there is a link with the error at step 10_T3_20 ? I am available for a call

**Comment by dado330** [comment]
In attachment ([10_T3_20.zip](https://github.com/user-attachments/files/16557887/10_T3_20_create_prevalence_of_exclusive_use_MSmeds_in_MSpregnancy_trimesters.zip)) a revised step 10_T3_20 to test.

Please open an issue regarding step 09_T3_20. As you can see in the [Flowchart](https://imi-conception.github.io/DP3-MS-SLE/diagram_draft.html) it is necessary for templates 8 and 10 in EFEMERIS.

**Comment by mariebeslay** [comment]
Thanks, it works now for the step 10_T3_20
