### ISSUE TITLE
Running DP3 on the whole population

### ISSUE THREAD

**Issue by SHayati** [IMI-ConcePTION/DP3-MS-SLE#26]
Hi,
While trying to run the latest release of DP3 on the whole population in UOSL, I received the following error:

![image](https://github.com/user-attachments/assets/61b8f3f0-e892-429d-ba1c-64e1c6b68e8d)

**Comment by DavideMessinaARS** [comment]
Which version are you running?

Anyway, this error means the script does not find the directory specified in the parameter dirpregnancy. You can set this parameter from the file 01_parameters_program.R in the folder p_parameters

**Comment by SHayati** [comment]
This is DP3-MS-SLE v3.0.0-zeta. Previously we ran this script on both the whole population and also the pregnancy cohort. For running on the whole population I have left dirpregnancy<-""

**Comment by DavideMessinaARS** [comment]
I think you should populate it: the script otherwise won't know which are the pregnancies to be matched.

Anyway, v3.0.0-zeta should be run only by FERR. A new release will be available hopefully this week after v3.0.0 has been tested on FERR

**Comment by SHayati** [comment]
Thank you Davide. Please close the issue.
