### ISSUE TITLE
error in general parameters

### ISSUE THREAD

**Issue by erarasfisabio** [IMI-ConcePTION/DP3-MS-SLE#27]
Dear, 
After having modified the parameter dirinputs, when we wxwcute the parameters in the torun file, this error appears: 

> source(paste0(thisdir,"/p_parameters/01_parameters_program.R")) #GENERAL Error in gzfile(file, mode) : cannot open the connection In addition: Warning message: In gzfile(file, mode) :   cannot open compressed file 'D:\Users\533781~1\AppData\Local\Temp\Rtmpy23Yoa/libloc_210_b62864a0.rds', probable reason 'No such file or directory'
--
 
Please, could you provide some feedback to solve this?
Best,
Laia

**Comment by DavideMessinaARS** [comment]
Normally this error happens when dirinput has not been specified correctly. Can you double check if it is correct?

**Comment by erarasfisabio** [comment]
laia.barrachina@fisabio.es 
we can use teams also

**Comment by erarasfisabio** [comment]
Thaks for your support the script is already running
