### ISSUE TITLE
Error during wrapup

### ISSUE THREAD

**Issue by erarasfisabio** [IMI-ConcePTION/DP3-MS-SLE#28]
Hi @DavideMessinaARS 
The execution has stopped by another error:
Browse[5]> launch_step("p_steps/06_T3_20_apply_selection_criteria_to_pregnancies.R")
[1] "FLOWCHART"
Error during wrapup: cannot open the connection
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Timing stopped at: 0 0.03 0.03

R give us some actions: contuinue or stop
![DU-DP3](https://github.com/user-attachments/assets/8d3cbbfb-0d06-42b0-96f9-3494cb96be3a)

Can we check this?
best, Laia

**Comment by DavideMessinaARS** [comment]
The error is in 06_T3_10.

Please:
1) Stop the debug mode (red square button in the console pane)
2) Rerun the parameters again
3) Run just 06_T3_10
4) In case it was necessary please stop again the debug mode
5) Write ```traceback()``` in the console
6) Paste here the output of the console

**Comment by DavideMessinaARS** [comment]
In addition, can you please check if step 05_T2_30 is running without errors? Thanks

**Comment by erarasfisabio** [comment]
> The error is in 06_T3_10.
> 
> Please:
> 
>     1. Stop the debug mode (red square button in the console pane)
> 
>     2. Rerun the parameters again
> 
>     3. Run just 06_T3_10
> 
>     4. In case it was necessary please stop again the debug mode
> 
>     5. Write `traceback()` in the console
> 
>     6. Paste here the output of the console

**I have copyed the text below from the traceback window before stopping the debug. When it was stopped, the `traceback()` in the console,  returns** > traceback()
No traceback available 

_tracebacK: eval (substitute(browser(skipCalls 0 pos), list(pos = (length(sys.frames()) -frame) + 2)), envir = sys.frame(frame))_
readRDS(file_name) at Smart_load.R:13
smart_load("D3_DU_selection_criteris_from_pregnancies_to_DU_PREGNANCY_COHORT" ,  dirtemp, extension = extension) at Smart_load.R:13
[Debug source] at 06_T3_20_apply_selection_criteria_to_pregnancies.R:13

**Comment by DavideMessinaARS** [comment]
I think it says it doesn't find the input dataset of the step.
Can you please check if step 05_T2_30 is running without errors?

**Comment by erarasfisabio** [comment]
> In addition, can you please check if step 05_T2_30 is running without errors? Thanks

**Sure!**
<html>
<body>

launch_step("p_steps/05_T2_30_create_selection_criteria_from_pregnancies.R") Error: 'months' is not an exported object from 'namespace:lubridate' Called from: eval(ei, envir)
--
 
Browse[1]> | Browse[1]>
Browse[1]>


</body>
</html>
AND THE TRACEBACK
<html>
<body>

traceback() 6: eval(ei, envir) 5: eval(ei, envir) 4: withVisible(eval(ei, envir)) 3: source(paste0(thisdir, "/", x)) at launch_step.R#9 2: system.time(source(paste0(thisdir, "/", x))) at launch_step.R#9 1: launch_step("p_steps/05_T2_30_create_selection_criteria_from_pregnancies.R")
--
 
> | >
>


</body>
</html>

**Comment by erarasfisabio** [comment]
Sorry Davide, I have to leave. Does it works for you to check this tomorrow? I will be available 9 to 15.

**Comment by DavideMessinaARS** [comment]
Please extract [05_T2_30_create_selection_criteria_from_pregnancies.zip](https://github.com/user-attachments/files/17952730/05_T2_30_create_selection_criteria_from_pregnancies.zip) in p_steps. Then rerun the parameters and from 05_T2_30 onwards.

**Comment by erarasfisabio** [comment]
Dear Davide, 
at the beginning your proposal seemed to work, but unfortunately it gave an error and stopped.

Timing stopped at: 36.49 1.24 7382
> traceback()
6: eval(ei, envir)
5: eval(ei, envir)
4: withVisible(eval(ei, envir))
3: source(paste0(thisdir, "/", x)) at launch_step.R#9
2: system.time(source(paste0(thisdir, "/", x))) at launch_step.R#9
1: launch_step("p_steps/05_T2_30_create_selection_criteria_from_pregnancies.R")

**Comment by DavideMessinaARS** [comment]
The problem is the traceback R gives you this time seems to be incomplete. It is missing the last part where the error really occurred so I can't troubleshoot.
Are you available for a meeting now? If yes could you send me a Teams link?

**Comment by erarasfisabio** [comment]
sure. It is ok for me to meet now

**Comment by erarasfisabio** [comment]
Could you send me the lin? I am not sure on how to preceed to send you a link as you are an external member from my institution... sorry

**Comment by erarasfisabio** [comment]
Davide, 
I can't close the issue, it has happened again

Please see the shoot attached

I look forward to hearing from you next week.
Laia

![DIVENDRES](https://github.com/user-attachments/assets/5bcdb1d6-254f-46ff-aa6d-0f0a2bd7bfb1)

**Comment by DavideMessinaARS** [comment]
Did you left open the flowchart in excel/openoffice? The issue seems to be in step 06_T3_20.

Close the csv file and then rerun from 06_T3_20

**Comment by erarasfisabio** [comment]
Davide, although the csv file was not open, I re-run 06_T3_20 and it seems to have worked. Also 07_T2_10, and 08_T4_20.
 It has finished with "View(data_preparation_3)"
How should I proceed now?

**Comment by DavideMessinaARS** [comment]
"View(data_preparation_3)" is an internal function so I don't know why the script decided to open it.

If you are sure 06_T3_20, 07_T2_10 and 08_T4_20 run successfully please continue running with the remaining steps

**Comment by erarasfisabio** [comment]
Dear  @DavideMessinaARS, it seems they have run succesfully untill 08_T4_20, but in 
> launch_step("p_steps/09_T3_10_create_candidate_matches_MS_non_pregnant.R")
Error in rbindlist(list(complete_preg_cohort, ms_cohort_not_preg)) : 
  Class attribute on column 2 of item 2 does not match with column 2 of item 1.
Called from: rbindlist(list(complete_preg_cohort, ms_cohort_not_preg))

traceback: > Debug source in line 82 in ("p_steps/09_T3_10_create_candidate_matches_MS_non_pregnant.R")
Error in rbindlist(list(complete_preg_cohort, ms_cohort_not_preg)) : 
 
I look forward to hearing from you.
Laia

**Comment by erarasfisabio** [comment]
**Dear @DavideMessinaARS , 
although we have obtained the above error at "p_steps/09_T3_10_create_candidate_matches_MS_non_pregnant.R"
in the outputs folder the following files have been generated,** 
- D5_DU_flowchart_exclusion_criteria_from_pregnancies_to_DU_PREGNANCY_COHORT.csv
- D5_DU_flowchart_exclusion_criteria_from_SAP1_MS_cohort_to_DU_MS_cohort.csv
- D5_DU_for_Template_1.csv
- D5_DU_for_Template_2.csv
-D5_DU_for_Template_4.csv
-D5_DU_for_Template_5.csv
-D5_DU_for_Templates_8_11.csv
-D5_meaning_occurences.cvs
-Description_matched_preg_DU_MS.csv
- Flowchart_exclusion_criteria.csv
And for de DU_final_tables, templates 1 and 2.
**Could you tell us if this is enough and I should upload it to the DRE, or do we have to manage the error?**
we look forward to hearing from you. 
Laia

**Comment by DavideMessinaARS** [comment]
Sorry for the late reply.

Can you please run the following commands in the console then copy here the output?

``` r
sapply(complete_preg_cohort, class)
sapply(ms_cohort_not_preg, class)
```

If the environment of when the error occurred is still there it should work.
In case it won't then rerun the parameter, open step 09_T3_10_create_candidate_matches_MS_non_pregnant, run until line 81 and then use the commands above

**Comment by erarasfisabio** [comment]
Of course.
Here is the result. Now I have to attend a meeting until 14:00 please, if possible, tell me the next steps and if possible I will execute them today ;) 
![test](https://github.com/user-attachments/assets/db5bd0af-38c5-49b5-a37c-af98e0f91666)

**Comment by DavideMessinaARS** [comment]
Can we maybe schedule call for this afternoon? Is 14:30 ok for you?

**Comment by erarasfisabio** [comment]
Sure Davide, let's meet at 14:30

**Comment by erarasfisabio** [comment]
we are ready to upload the outputs. thank you for your support
