### ISSUE TITLE
Runtime error (UOSL)

### ISSUE THREAD

**Issue by SHayati** [IMI-ConcePTION/DP3-MS-SLE#29]
Hi,

The script stopped with the following error, while executed on UOSL CDM:
![image](https://github.com/user-attachments/assets/9c9f56ad-ffbb-440d-87c9-5b64bee3b209)

Any suggestion?

Best regards,
Saeed Hayati

**Comment by SHayati** [comment]
Hi,

Received the following error:
![image](https://github.com/user-attachments/assets/c36daed1-47bc-40bf-8cbd-0a662bdc106e)

**Comment by DavideMessinaARS** [comment]
Please open step 08_T4_20 and run until line 16. Then check if tmp1 and tmp2 have at least some rows

**Comment by SHayati** [comment]
one row in tmp1 and zero in tmp2. I am available for a short call if it helps.

**Comment by DavideMessinaARS** [comment]
Please extract [05_T2_30_create_selection_criteria_from_pregnancies.zip](https://github.com/user-attachments/files/17958305/05_T2_30_create_selection_criteria_from_pregnancies.zip) in p_steps. Then rerun the parameters and from /05_T2_30 onwards.

I noticed I used an incorrect filter for the pregnancies regarding quality.

**Comment by SHayati** [comment]
Solved.

Thank you Davide.
